POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "VS Code Rest Client",
    "number": "4324-43244242333"
}

###
GET http://localhost:3001/api/persons

###
DELETE http://localhost:3001/api/persons/60752283e782c608f0a0571c

###
DELETE http://localhost:3001/api/persons/hgfjsdhghfdfdsg

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Lord TryharDSDd",
    "number": "765484325"
}


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test",
    "number": "765484325"
}

###
PUT http://localhost:3001/api/persons/607518d3c067781e807e73f1
Content-Type: application/json

{
    "name": "VS Code Rest Client",
    "number": "99432432421"
}

###
GET http://localhost:3001/api/persons/606fd2cf7d2174426404241b